# #!/usr/bin/env python3
# # -*- coding: utf-8 -*-

# """
# PB2025 Sentry Strategy Node (Python Version)
# Author: PolarBear Team (Generated by AI)
# Description: 
#     实现了哨兵机器人的核心决策逻辑 (FSM)。
#     替代了原本的 behavior_trees/rmul_2025.xml。
    
# Features:
#     - 4分30秒强制启动机制
#     - 简单的状态机逻辑 (感知 -> 决策 -> 执行)
#     - 严格兼容原有的 Topic 接口
# """

# import math
# import rclpy
# from rclpy.node import Node
# from rclpy.qos import QoSProfile

# # 导入标准消息
# from geometry_msgs.msg import Twist, PoseStamped
# from example_interfaces.msg import Float32

# # 导入自定义消息 (依赖 pb_rm_interfaces)
# # 如果本地环境报错，请确保已 source install/setup.bash
# try:
#     from pb_rm_interfaces.msg import GameStatus, RobotStatus, RfidStatus
# except ImportError:
#     print("Error: Could not import pb_rm_interfaces. Make sure the package is built and sourced.")
#     raise

# class SentryStrategyNode(Node):
#     def __init__(self):
#         super().__init__('pb2025_sentry_strategy_node')

#         # ==================== 参数配置 ====================
#         self.FORCE_START_TIME_SEC = 270.0  # 4分30秒强制启动
#         self.LOOP_RATE_HZ = 10.0           # 控制循环频率
        
#         # 阈值配置 (参考 rmul_2025.xml)
#         self.HP_MIN = 200        # 血量低于此值进入生存模式
#         self.HEAT_MAX = 350      # 热量高于此值停止射击(策略层暂不控制开火，仅作状态判断)
#         self.AMMO_MIN = 0        # 弹丸阈值

#         # 目标点配置
#         self.ATTACK_POSE = (4.65, -3.5, 0.0)  # 进攻点 (x, y, yaw)
#         self.SUPPLY_POSE = (0.0, 0.0, 0.0)    # 补给点/安全点

#         # ==================== 状态变量 ====================
#         self.start_time = self.get_clock().now()
        
#         # 数据缓存 (初始化为 None 以区分是否收到过消息)
#         self.latest_game_status = None
#         self.latest_robot_status = None
#         self.latest_rfid_status = None

#         # ==================== 通信接口 ====================
#         qos = QoSProfile(depth=10)

#         # 1. 订阅者 (保持话题名不变)
#         self.sub_game = self.create_subscription(
#             GameStatus, 'referee/game_status', self.game_status_cb, qos)
#         self.sub_robot = self.create_subscription(
#             RobotStatus, 'referee/robot_status', self.robot_status_cb, qos)
#         self.sub_rfid = self.create_subscription(
#             RfidStatus, 'referee/rfid_status', self.rfid_status_cb, qos)

#         # 2. 发布者 (保持话题名不变)
#         self.pub_vel = self.create_publisher(Twist, 'cmd_vel', qos)
#         self.pub_spin = self.create_publisher(Float32, 'cmd_spin', qos)
#         self.pub_goal = self.create_publisher(PoseStamped, 'goal_pose', qos)

#         # 3. 定时器 (主循环)
#         self.timer = self.create_timer(1.0 / self.LOOP_RATE_HZ, self.control_loop)
        
#         self.get_logger().info("Sentry Strategy Node (Python) Started. Waiting for Game Start or Timeout...")

#     # ==================== 回调函数 ====================
#     def game_status_cb(self, msg):
#         self.latest_game_status = msg

#     def robot_status_cb(self, msg):
#         self.latest_robot_status = msg

#     def rfid_status_cb(self, msg):
#         self.latest_rfid_status = msg

#     # ==================== 核心逻辑 ====================
#     def control_loop(self):
#         """
#         主控制循环：感知 -> 决策 -> 执行
#         """
#         # 1. 检查比赛是否开始
#         if not self.is_game_running():
#             self.stop_robot()
#             return

#         # 2. 比赛进行中：基础动作
#         # 对应 XML: <PublishSpinSpeed spin_speed="7.0" .../>
#         self.publish_spin_speed(7.0)

#         # 3. 状态决策
#         if self.is_robot_healthy():
#             # === 状态良好：进攻/巡逻 ===
#             # 对应 XML: <PubNav2Goal goal="4.65;-3.5;0" .../>
#             self.get_logger().debug("State: Attack/Patrol", throttle_duration_sec=2.0)
#             self.publish_nav_goal(*self.ATTACK_POSE)
#         else:
#             # === 状态不佳：生存/补给 ===
#             self.get_logger().warn("State: Survival/Resupply", throttle_duration_sec=2.0)
#             self.execute_survival_logic()

#     # ==================== 判断逻辑 ====================
#     def is_game_running(self):
#         """
#         判断比赛是否开始，包含强制启动逻辑
#         """
#         # 逻辑 A: 时间强制启动
#         elapsed = (self.get_clock().now() - self.start_time).nanoseconds / 1e9
#         if elapsed > self.FORCE_START_TIME_SEC:
#             self.get_logger().info("Force Start Activated (Timeout > 4m30s)", throttle_duration_sec=5.0)
#             return True

#         # 逻辑 B: 裁判系统数据
#         if self.latest_game_status is None:
#             return False
        
#         # game_progress = 4 代表比赛进行中
#         if self.latest_game_status.game_progress == 4:
#             return True
            
#         return False

#     def is_robot_healthy(self):
#         """
#         判断机器人是否健康 (血量、热量、弹丸)
#         对应 XML: check_robot_status -> IsStatusOK
#         """
#         if self.latest_robot_status is None:
#             return True # 默认健康，防止没数据时发呆
        
#         s = self.latest_robot_status
#         is_hp_ok = s.current_hp >= self.HP_MIN
#         is_heat_ok = s.shooter_17mm_1_barrel_heat <= self.HEAT_MAX
#         is_ammo_ok = s.projectile_allowance_17mm >= self.AMMO_MIN
        
#         return is_hp_ok and is_heat_ok and is_ammo_ok

#     def execute_survival_logic(self):
#         """
#         生存模式逻辑
#         对应 XML: check_robot_status -> Fallback (IsRfidDetected or PubNav2Goal)
#         """
#         # 检查是否已经在补给区 (不重叠区域)
#         in_supply_zone = False
#         if self.latest_rfid_status:
#             # friendly_supply_zone_non_exchange == 1 (DETECTED)
#             if self.latest_rfid_status.friendly_supply_zone_non_exchange == 1:
#                 in_supply_zone = True
        
#         if in_supply_zone:
#             # 已经在补给区，保持静止或微调
#             # 这里为了简单，我们不再发布目标点，或者发当前点，避免干扰补给
#             # 原逻辑中如果 IsRfidDetected 成功，就不会执行后面的 PubNav2Goal
#             pass 
#         else:
#             # 不在补给区，前往补给点
#             self.publish_nav_goal(*self.SUPPLY_POSE)

#     # ==================== 执行动作 ====================
#     def stop_robot(self):
#         """停止所有运动"""
#         self.publish_spin_speed(0.0)
#         self.pub_vel.publish(Twist()) # 发送零速度

#     def publish_spin_speed(self, speed):
#         """发布小陀螺速度"""
#         msg = Float32()
#         msg.data = float(speed)
#         self.pub_spin.publish(msg)

#     def publish_nav_goal(self, x, y, yaw):
#         """发布导航目标点 (欧拉角转四元数)"""
#         msg = PoseStamped()
#         msg.header.stamp = self.get_clock().now().to_msg()
#         msg.header.frame_id = "map"
        
#         msg.pose.position.x = float(x)
#         msg.pose.position.y = float(y)
#         msg.pose.position.z = 0.0

#         # Yaw 转四元数
#         cy = math.cos(yaw * 0.5)
#         sy = math.sin(yaw * 0.5)
#         msg.pose.orientation.w = cy
#         msg.pose.orientation.z = sy
#         msg.pose.orientation.x = 0.0
#         msg.pose.orientation.y = 0.0

#         self.pub_goal.publish(msg)

# def main(args=None):
#     rclpy.init(args=args)
#     node = SentryStrategyNode()
#     try:
#         rclpy.spin(node)
#     except KeyboardInterrupt:
#         pass
#     finally:
#         node.destroy_node()
#         rclpy.shutdown()

# if __name__ == '__main__':
#     main()




#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import math
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile
from geometry_msgs.msg import Twist, PoseStamped
from example_interfaces.msg import Float32

# 导入自定义消息
try:
    from pb_rm_interfaces.msg import GameStatus, RobotStatus, RfidStatus
except ImportError:
    print("Error: Could not import pb_rm_interfaces. Make sure the package is built and sourced.")
    raise

class SentryStrategyNode(Node):
    def __init__(self):
        super().__init__('pb2025_sentry_strategy_node')

        # ==================== 参数配置 ====================
        self.FORCE_START_TIME_SEC = 270.0  
        self.LOOP_RATE_HZ = 10.0           
        self.DATA_TIMEOUT_SEC = 2.0        # 数据超时阈值：2秒没收到消息视为丢包/断连

        # 阈值配置
        self.HP_MIN = 200        
        self.HEAT_MAX = 350      
        self.AMMO_MIN = 0        

        self.ATTACK_POSE = (4.65, -3.5, 0.0)  
        self.SUPPLY_POSE = (0.0, 0.0, 0.0)    

        # ==================== 状态变量 ====================
        self.start_time = self.get_clock().now()
        
        # 数据缓存及时间戳（用于监测“某话题没数据”）
        self.latest_game_status = None
        self.last_game_time = 0.0
        
        self.latest_robot_status = None
        self.last_robot_time = 0.0
        
        self.latest_rfid_status = None
        self.last_rfid_time = 0.0

        # ==================== 通信接口 ====================
        qos = QoSProfile(depth=10)

        # 定义订阅信息用于后续检查
        self.topic_info = {
            'game': 'referee/game_status',
            'robot': 'referee/robot_status',
            'rfid': 'referee/rfid_status'
        }

        self.sub_game = self.create_subscription(
            GameStatus, self.topic_info['game'], self.game_status_cb, qos)
        self.sub_robot = self.create_subscription(
            RobotStatus, self.topic_info['robot'], self.robot_status_cb, qos)
        self.sub_rfid = self.create_subscription(
            RfidStatus, self.topic_info['rfid'], self.rfid_status_cb, qos)

        self.pub_vel = self.create_publisher(Twist, 'cmd_vel', qos)
        self.pub_spin = self.create_publisher(Float32, 'cmd_spin', qos)
        self.pub_goal = self.create_publisher(PoseStamped, 'goal_pose', qos)

        # 启动自检定时器 (检查话题是否存在)
        self.create_timer(3.0, self.check_topic_connectivity)
        
        # 主循环定时器
        self.timer = self.create_timer(1.0 / self.LOOP_RATE_HZ, self.control_loop)
        
        self.get_logger().info("Sentry Strategy Node Initialized. System Health Monitoring Active.")

    # ==================== 报错与监测逻辑 ====================
    def check_topic_connectivity(self):
        """检查是否有其他节点在发布这些话题"""
        for key, topic in self.topic_info.items():
            count = self.count_publishers(topic)
            if count == 0:
                self.get_logger().error(f"TOPIC MISSING: No publishers found for [{topic}]. Is the Serial/Referee node running?")

    def check_data_freshness(self):
        """检查数据是否还在更新"""
        now = self.get_clock().now().nanoseconds / 1e9
        
        # 检查比赛状态数据
        if self.latest_game_status is None:
            self.get_logger().warn(f"NO DATA: Never received [{self.topic_info['game']}]", throttle_duration_sec=10.0)
        elif (now - self.last_game_time) > self.DATA_TIMEOUT_SEC:
            self.get_logger().error(f"DATA TIMEOUT: [{self.topic_info['game']}] stopped updating!", throttle_duration_sec=5.0)

        # 检查机器人状态数据
        if self.latest_robot_status is None:
            self.get_logger().warn(f"NO DATA: Never received [{self.topic_info['robot']}]", throttle_duration_sec=10.0)
        elif (now - self.last_robot_time) > self.DATA_TIMEOUT_SEC:
            self.get_logger().error(f"DATA TIMEOUT: [{self.topic_info['robot']}] stopped updating!", throttle_duration_sec=5.0)

    # ==================== 回调函数 ====================
    def game_status_cb(self, msg):
        self.latest_game_status = msg
        self.last_game_time = self.get_clock().now().nanoseconds / 1e9

    def robot_status_cb(self, msg):
        self.latest_robot_status = msg
        self.last_robot_time = self.get_clock().now().nanoseconds / 1e9

    def rfid_status_cb(self, msg):
        self.latest_rfid_status = msg
        self.last_rfid_time = self.get_clock().now().nanoseconds / 1e9

    # ==================== 核心逻辑 ====================
    def control_loop(self):
        # 实时监测数据新鲜度
        self.check_data_freshness()

        # 1. 检查比赛是否开始
        if not self.is_game_running():
            self.stop_robot()
            return

        # 2. 执行基础动作
        self.publish_spin_speed(7.0)

        # 3. 状态决策
        if self.is_robot_healthy():
            self.get_logger().debug("State: Attack/Patrol", throttle_duration_sec=5.0)
            self.publish_nav_goal(*self.ATTACK_POSE)
        else:
            self.execute_survival_logic()

    def is_game_running(self):
        elapsed = (self.get_clock().now() - self.start_time).nanoseconds / 1e9
        
        # 强制启动优先
        if elapsed > self.FORCE_START_TIME_SEC:
            self.get_logger().info("Mode: Force Start (Timeout)", throttle_duration_sec=10.0)
            return True

        # 裁判系统数据检查
        if self.latest_game_status is None:
            # 此处不报错，由 check_data_freshness 处理，仅提示等待
            return False
        
        if self.latest_game_status.game_progress == 4:
            return True
        
        self.get_logger().info(f"Waiting: Game Progress is {self.latest_game_status.game_progress}", throttle_duration_sec=10.0)
        return False

    def is_robot_healthy(self):
        if self.latest_robot_status is None:
            # 这种情况下无法判断健康度，安全起见报错并默认健康以维持运动
            self.get_logger().error("Decision Logic: Missing RobotStatus, defaulting to HEALTHY to avoid freeze.")
            return True 
        
        s = self.latest_robot_status
        is_hp_ok = s.current_hp >= self.HP_MIN
        is_heat_ok = s.shooter_17mm_1_barrel_heat <= self.HEAT_MAX
        is_ammo_ok = s.projectile_allowance_17mm >= self.AMMO_MIN
        
        if not is_hp_ok:
            self.get_logger().warn(f"Health Low: HP {s.current_hp} < {self.HP_MIN}", throttle_duration_sec=2.0)
        if not is_heat_ok:
            self.get_logger().warn(f"Heat High: {s.shooter_17mm_1_barrel_heat} > {self.HEAT_MAX}", throttle_duration_sec=2.0)
        
        return is_hp_ok and is_heat_ok and is_ammo_ok

    def execute_survival_logic(self):
        in_supply_zone = False
        if self.latest_rfid_status:
            if self.latest_rfid_status.friendly_supply_zone_non_exchange == 1:
                in_supply_zone = True
        else:
            self.get_logger().warn("Survival Logic: RFID data missing, moving to supply pose by default.")

        if in_supply_zone:
            self.get_logger().info("Status: Resupplying...", throttle_duration_sec=5.0)
        else:
            self.get_logger().warn("Status: Returning to Supply Station", throttle_duration_sec=2.0)
            self.publish_nav_goal(*self.SUPPLY_POSE)

    # ==================== 执行动作 ====================
    def stop_robot(self):
        self.publish_spin_speed(0.0)
        self.pub_vel.publish(Twist())

    def publish_spin_speed(self, speed):
        msg = Float32()
        msg.data = float(speed)
        self.pub_spin.publish(msg)

    def publish_nav_goal(self, x, y, yaw):
        msg = PoseStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = "map"
        msg.pose.position.x = float(x)
        msg.pose.position.y = float(y)
        
        cy = math.cos(yaw * 0.5)
        sy = math.sin(yaw * 0.5)
        msg.pose.orientation.w = cy
        msg.pose.orientation.z = sy
        self.pub_goal.publish(msg)

def main(args=None):
    rclpy.init(args=args)
    node = SentryStrategyNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()